/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { TabBarData } from 'lib_common';

export class ConstantsHome {
  /**
   * id of avoid message event.
   */
  static readonly AVOID_EVENT_ID: number = 1;
  /**
   * border of image.
   */
  static readonly IMAGE_BORDER: number = 12;
  /**
   * border of button.
   */
  static readonly BUTTON_BORDER: number = 6;
  /**
   * number keyboard key.
   */
  static readonly NUMBER_KEYBOARD: string = 'Number';
  /**
   * english keyboard key.
   */
  static readonly ENGLISH_KEYBOARD: string = 'English';
  /**
   * system keyboard key.
   */
  static readonly SYSTEM_KEYBOARD: string = 'System';
  /**
   * the initial top padding of main page.
   */
  static readonly MAIN_PAGE_INITIAL_PADDING: number = 210;
  /**
   * the radius of button in keyboard.
   */
  static readonly KEYBOARD_BUTTON_RADIUS: number = 6;
  /**
   * the fontsize of button in keyboard.
   */
  static readonly KEYBOARD_BUTTON_FONTSIZE_18: number = 18;
  /**
   * the fontsize of button in keyboard.
   */
  static readonly KEYBOARD_BUTTON_FONTSIZE_20: number = 20;
  /**
   * the space between button in english keyboard.
   */
  static readonly ENGLISH_KEYBOARD_BUTTON_SPACE: number = 6;
  /**
   * the default space in column.
   */
  static readonly DEFAULT_COLUMN_SPACE: number = 12;
  /**
   * Resource type media.
   */
  static readonly RESOURCE_TYPE_MEDIA: number = 20000;
  static readonly SERVICE_LOST_TABS: TabBarData[] = [
    {
      id: 0,
      title: '物品寄存'
    },
    {
      id: 1,
      title: '失物招领'
    }
  ]
}